---
# tasks file for roles/sample-apache
- ansible.builtin.dnf:
    name: 
      - httpd
      -  mod_ssl
      - php
         
    state: latest

- ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes
     
- ansible.posix.firewalld:
    port: "{{item}}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp

- ansible.builtin.template:
    src: index.html.j2 
    dest: /var/www/html/index.html 
  notify: restart httpd    

