---
- hosts: all
  become: yes
  tasks:
    - ansible.builtin.copy:
        content: " welcome to haproxy"
        dest: /etc/motd
      when: inventory_hostname in groups['proxy']    

    - ansible.builtin.copy:
        content: " welcome to web"
        dest: /etc/motd
      when: inventory_hostname in groups['web']
    

    - ansible.builtin.copy:
        content: " welcome to data"
        dest: /etc/motd
      when: inventory_hostname in groups['data']
    

    - ansible.builtin.copy:
        content: " welcome to test"
        dest: /etc/motd
      when: inventory_hostname in groups['test']
    

     

      
