---
- name: Ping Cisco devices
  hosts: cisco_devices  # Replace with your inventory group or host pattern
  gather_facts: no  # Disable fact gathering for faster execution

  tasks:
    - name: Ping a specific IP address
      ios_ping:
        dest: 8.8.8.8  # Replace with the IP address you want to ping
        count: 5  # Number of ping packets to send
      register: ping_result

    - name: Display the ping result
      debug:
        var: ping_result
