---
- hosts: all
  become: yes
  vars_files:
    - locker.yml
    - new_user.yml

  tasks:
    - ansible.builtin.group:
        name: "{{item}}"
        state: present
      loop:
        - devops
        - opsmgr

    - ansible.builtin.user:
        name: "{{item.name}}"
        groups: devops
        password: "{{ pw_developer | password_hash('sha512') }}"
        update_password: on_create
      loop: "{{users}}"
      when: inventory_hostname in groups['data'] or inventory_hostname in groups['test'] and item.Job == 'developer'

    - ansible.builtin.user:
        name: "{{item.name}}"
        groups: opsmgr
        password: "{{ pw_manager | password_hash('sha512') }}"
        update_password: on_create
      loop: "{{users}}"
      when: inventory_hostname in groups['proxy'] or inventory_hostname in groups['prod'] and item.Job == 'manager'


    
