---
- hosts: web
  become: yes
  vars_files:
    - secret.yml
    - vars/user_list.yml  
  tasks:
    - ansible.builtin.user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        shell: /bin/bash
        groups: wheel
        password: "{{ user_password | password_hash('sha512') }}"
        update_password: on_create
      loop: "{{users}}"
      when: item.uid >= 1000



- hosts: data
  become: yes

  tasks:
    - ansible.builtin.user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        shell: /bin/bash
        groups: wheel
        password: "{{ user_password | password_hash('sha512') }}"
        update_password: on_create
      loop: "{{users}}"
      when: item.uid >= 2000        
